# apps/portal/nginx.conf
server {
    listen 80;
    server_name dashboard.ethikslabs.com;
    root /home/ec2-user/portal/dist;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location ~* \.(js|css|png|jpg|svg|ico|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
